### ISSUE TITLE
Run robot with type 2 sample holder

### ISSUE THREAD

**Issue by dooryhee** [xpdAcq/mission-control#119]
## Summary
Sequence of robot commands depends on sample holder type.

## Expected Behavior
Type 1 sample holder (capillary): load sample- take data-unload sample. 
Type 2 sample holder (flat plate in reflection): as above.  
Type 2 sample holder (flat plate in transmission): load sample - rotate 90degree- take data -rotate-90 degrees-unload sample.

## Current Behavior
Type 2 sample holder transmission operations is not supported by current xpdAcq robot commands.
Sample needs to be rotated (goniometer omega axis). Rotation is generally counter-clockwise, i.e. +90degrees. However negative relative rotation should be left optional.

## Proposed solution
Make it completely general, regardless of the sample holder type: load sample - rotate omega - take data -rotate -omega -unload sample, where omega is any value in the [-100,100] interval.

## Context
Expecting to run the robot in type 2 transmission mode on June 15th.

**Comment by CJ-Wright** [comment]
Is there an ophyd object to the omega motor?

**Comment by CJ-Wright** [comment]
It seems that the relevant motor is called `th` https://github.com/NSLS-II-XPD/ipython_ophyd/blob/master/profile_collection/startup/10-motors.py#L19

**Comment by dooryhee** [comment]
Yes, that’s the one.
E

**Comment by CJ-Wright** [comment]
I think this may be a good reason to support magazine sheet(s) in the sample spreadsheet. This would allow us to:
1. Separate sample metadata from robot metadata
1. Make running of the robot easier
1. Provide a nicer interface for specifying scans for the samples

**Comment by sbillinge** [comment]
what is the status of this issue?

**Comment by CJ-Wright** [comment]
I think there are a couple todos left on this:
- [ ] Make the move relative for all the sample holders
- [ ] Implement a second (or at least second tab) spreadsheet for handling robot things
    - [ ] Build schema for spreadsheet (what do we need in the way of information)
    - [ ] Make parser for spreadsheet.

**Comment by CJ-Wright** [comment]
We need to change the move to a relative move, which we need to code ourselves since this is inside the device and not in a plan, I think.

**Comment by sbillinge** [comment]
I agree with Chris.

I would rather that we come up with a robust solution that captures all the
likely UCs than just hack something together.

Can we capture some UCs?

S

**Comment by dooryhee** [comment]
- user makes sure 1) robot is trained and ready; 2) diffractometer is in the right configuration i.e. right height and omega in particular; 3) omega increment (Dom) is known, where Dom is any value in the [-100,100] interval; 4) no risk of collision
- robot loads sample
- rotate omega relative by Dom  (if no motion is required , Dom = 0)
- search sample (optional)
- take data
- rotate omega back relative by -Dom
- unload sample
- repeat

**Comment by CJ-Wright** [comment]
@dooryhee @sghose @adelezh The work for making plate geometries rotate for transmission was done today.

**Comment by CJ-Wright** [comment]
Now we need a way for xpdAcq to be aware of the sample geometry.

**Comment by CJ-Wright** [comment]
xref: https://github.com/xpdAcq/xpdAcq/pull/524

**Comment by CJ-Wright** [comment]
I think this is done

**Comment by CJ-Wright** [comment]
xref: https://github.com/xpdAcq/xpdAcq/pull/513

**Comment by CJ-Wright** [comment]
xref: https://github.com/NSLS-II-XPD/ipython_ophyd/pull/34
