### ISSUE TITLE
Analysis Database

### ISSUE THREAD

**Issue by CJ-Wright** [xpdAcq/mission-control#30]
Put data from the analysis pipeline into a database for storage, retrieval and mining.
### Usage
1. Data is processed via a pipeline, that data is then saved into a database for later retrieval.
1. User searches database for data, finds that data
    1. User searches by `sample_name` and `analysis_stage`
    1. User searches by `beamtime_uid` and `analysis_stage`
    1. User filters by provenance (eg. python version) and date ran

### Core concept
SHED mostly speaks the event model so we can push the outputs of most mutating nodes (`map`, `filter`, `accumulate`, etc.) into the databroker directly.  This means that not only raw data + metadata are stored in databroker fronted databases but also downstream data.  This will make it very easy to adapt and then rerun analysis graphs since it will just dip into the database to find the result of each mutating node.

### Implementational aspects
One issue will be to decide whether to store inputs or outputs of a calculation as the result of a node, which will depend on some metric that takes into account computation time vs. disk footprint.  One potential solution is to store stubs, starts and stops which have enough metadata to reproduce the data on demand without storing it.

Another issue which must be addressed is how to store information about the non-mutating nodes. Non-mutating nodes (`zip`, `combine_latest`, `zip_latest`, etc.) do not store information about how the operate (otherwise they'd be mutating nodes). As such they are invisible when only looking at the stored documents. For example a `map` of a `zip` would only show that two sources were together at the `zip`. However, we could get the exact same observed result via a `zip_latest` which could produce different results in the data. Thus, to properly store the metadata of the pipeline we need to somehow track what non-mutating nodes were used.

TODO:
---------
- [ ] Write sink for data (CJ)
- [ ] Write sink for stub (CJ)
- [ ] Store information on non-mutating nodes (CJ)
- [ ] Reload/recreate data from stubs (CJ) 
- [ ] Re-running pipeline loads from disk rather than from recalculation, optionally and partially
- [ ] Write hierarchical data retrieval methods (`get_parents`, `get_children`, `get_relatives`) __(DAMA group?)__   
- [ ] Write shortcuts for getting analyzed data given raw metadata eg `db.search_by_raw(raw_md={'sample_name': 'Ni'}, analysis_stage='gr')` which is a proxy for searching the raw database for all the headers which match the raw_md and propagating them all down to G(r). __(DAMA group?)__
- [ ] Write meta-databroker to handle raw and analyzed data? Or maybe this is a header/event source? __(DAMA group?)__

**Comment by sbillinge** [comment]
Yes, this looks almost perfect Chris.  Here are a few comments

1) I think this activity is really important.  It will determine whether and how useful the data analysis pipeline is for complex heterogeneous data analyses (we know pipelines are useful for making sausages where the same thing is done every time like computed tomography, or real-time 2D to 1D powder data reduction).
2) I think we won't know exactly how to do this right until people start using it and we see how they use it and what difficulties they are having.  We should definitely be agile here.   This refers to "Usage".  I think working up some more concrete UCs that are sufficiently simple that they are concrete but sufficiently complex that they test the infrastructure would be good.  Can we meet, maybe with Max before he leaves, and get some kind of sample workflow from him?
3) The basic plumbing looks solid....two types of nodes (mutating or not), two types of DB saves (stubs or output).  This doesn't need too much discussion right now (maybe in the implementation details)
4) I guess you will be adding the database part and the roll-out later?
5) Target audience could be Elizabeth (who is less invested in fit2D) and maybe Long?

**Comment by CJ-Wright** [comment]
2. Ok I think those can go in the initial Epic description (if you have some off the top of your head please feel free to edit the top comment)
3. I suspect that we will have most of the implementation discussion in the issues that get attached to this.
4. I'm not certain what you mean, this is just a feature request (albeit a massive one that may get a release by itself) so it doesn't have all the info that a release definition needs.
5. Ok

**Comment by sbillinge** [comment]
Please create a new organization or reuse billingegroup organization and make a release milestone there for these developments.

**Comment by CJ-Wright** [comment]
Use Cases
----------------
### UC1
1. User has data in databases
1. User searches for all processed data associated with sample
1. User selects reduced data from results

### UC2
1. User has data in databases
1. User searches for graph associated with sample
1. User visualizes the graph

### UC3
1. As UC2
1. User modifies graph
1. User runs graph on data
1. Data is stored in database with new graph

### UC4
1. Graph has DOI associated with it
1. User loads Graph from DOI

### UC5
1. User finds all data which was run through a specific Graph

**Comment by CJ-Wright** [comment]
One approach to provenance for the pipeline is to:
1. walk the tree up to the raw data and generate a graph
1. go to each node in the graph and create a provenance dict
1. store this dict laden graph into the saved start/stop document with the data

This will allow us to recreate the graph (assuming well behaved maps and such) on retrieval. Additionally this will even capture non-mutating elements in the graph since they will have their nodes in the stored graph.

**Comment by sbillinge** [comment]
move to LDRD milestone/project

However, do we want a new issue that when this is working it is deployed at XPD?  we could link that issue to an XPD/PDF release milestone

**Comment by CJ-Wright** [comment]
It would be good to ship this out to its own process so it doesn't impact us. This could be done via the ZMQ dispatcher but we need the multiplexing support to make it work.
